Repository RedisAI/redisai-go, pull requests merged in 2020-05, with the labels that each got.

#9 [add] added AI.INFO to the supported commands list
  README.md
Labels: documentation

#8 Add support for AI.DAGRUN AI.DAGRUN_RO
  redisai/commands.go
  redisai/commands_test.go
  redisai/dag.go
Labels: enhancement

#10 [add] extended negative testing on tensor, model, and client
  redisai/client_test.go
  redisai/model_test.go
  redisai/tensor_test.go
Labels: enhancement

#12 Added an example on how to use an SSL Connection with RedisAI
  .circleci/config.yml
  .gitignore
  Makefile
  examples/redisai_tls_client/redisai_tls_client.go
  redisai/client_test.go
  redisai/example_client_test.go
Labels: documentation

#16 Added 3 examples on how to connect to the RedisAI Server. ( simplest way possible, with pool, and with SSL )
  redisai/client.go
  redisai/example_client_test.go
Labels: documentation

#19 normalize int(32) usage to int64
  README.md
  examples/redisai_pipelined_client/main.go
  examples/redisai_simple_client/main.go
  examples/redisai_tls_client/redisai_tls_client.go
  redisai/client_test.go
  redisai/commands.go
  redisai/commands_test.go
  redisai/dag.go
  redisai/example_client_test.go
  redisai/example_commands_test.go
  redisai/implementations/AIModel.go
  redisai/implementations/AITensor.go
  redisai/tensor.go
  redisai/tensor_test.go
Labels: breaking-change

#22 Support for [BATCHSIZE n [MINBATCHSIZE m]] in MODELSET
  redisai/commands_test.go
  redisai/implementations/AIModel.go
  redisai/model.go
Labels: enhancement

#25 Support for BACKENDSPATH <path> on AI.CONFIG
  redisai/commands.go
  redisai/commands_test.go
Labels: enhancement
